name: Build on Oracle Test Pilot

on:
  push:
    branches:
      - 'main'
      - 'otp-integration'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  dpy_tests-otp:
    permissions:
      contents: read
    name: Build python-oracledb driver
    #TODO
    #if: ${{ github.repository_owner == 'oracle' }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        rdbms: ['base-database-service-26ai','autonomous-transaction-processing-serverless-26ai']
    runs-on: [ self-hosted, Linux, X64, OracleTestPilot ]
    steps:

      - name: Check out python-oracledb repository code
        uses: actions/checkout@v5
        with:
          submodules: true
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create safe environment variable
        run: |
          PY_VERSION_SAFE="${{ matrix.python-version//./_ }}"
          echo "PY_VERSION_SAFE=$PY_VERSION_SAFE" >> $GITHUB_ENV
        shell: bash

      - id: create_database
        uses: oracle-actions/setup-testpilot@f620f11f9f26dacfe80ba1823342e3e92604c55f # v1.0.23
        with:
          oci-service: ${{ matrix.rdbms }}
          action: create
          user: pythontest_$PY_VERSION_SAFE,admin_$PY_VERSION_SAFE,pythontestproxy_$PY_VERSION_SAFE

#      - name: Install Oracle Instant Client
#        run: |
#          chmod +x ${{ github.workspace }}/.github/scripts/install_oracle_instantclient.sh
#          ${{ github.workspace }}/.github/scripts/install_oracle_instantclient.sh
#          echo "OIC_DIR=$(echo /opt/oracle/instantclient*)" >> $GITHUB_ENV

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test]"
          touch /home/ubuntu/tnsnames.ora

      - name: Run tests
        env:
          PYO_TEST_CONNECT_STRING: ${{ steps.create_database.outputs.connection_string_suffix }}
          PYO_TEST_MAIN_USER: pythontest_$PY_VERSION_SAFE_${{ github.run_number }}
          PYO_TEST_MAIN_PASSWORD: ${{ steps.create_database.outputs.database_password }}
          PYO_TEST_PROXY_USER: pythontestproxy_$PY_VERSION_SAFE_${{ github.run_number }}
          PYO_TEST_PROXY_PASSWORD: ${{ steps.create_database.outputs.database_password }}
          PYO_TEST_ADMIN_USER: admin_$PY_VERSION_SAFE_${{ github.run_number }}
          PYO_TEST_ADMIN_PASSWORD: ${{ steps.create_database.outputs.database_password }}
          PYO_TEST_EDITION_NAME: pythoneditions_$PY_VERSION_SAFE_${{ github.run_number }}
          TNS_ADMIN: /home/ubuntu
          LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}:/home/ubuntu
        run: |
          export PYO_TEST_CONNECT_STRING=`echo "${PYO_TEST_CONNECT_STRING:1:-1}"`
          python -m pytest tests/create_schema.py
#          python -m pytest
#          python -m pytest tests/create_schema.py
#          python -m pytest --use-thick-mode

      - id: delete_database
        uses: oracle-actions/setup-testpilot@f620f11f9f26dacfe80ba1823342e3e92604c55f # v1.0.23
        if: always()
        with:
          oci-service: ${{ matrix.rdbms }}
          action: delete
          user: pythontest_${{ matrix.python-version }}
